---
- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
    - name: start and enable web server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Deploy index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body><h1>Apache HTTPD is running!</h1></body>
          </html>
